-- ============================================================
-- RiskLens AI - AML Investigation Copilot
-- Step 1: Schema and Table Setup
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS AML_COPILOT;
CREATE SCHEMA IF NOT EXISTS AML_COPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS AML_COPILOT.PIPELINE;
CREATE SCHEMA IF NOT EXISTS AML_COPILOT.ANALYTICS;

USE DATABASE AML_COPILOT;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- RAW SCHEMA: Core Data Tables
-- ============================================================

CREATE OR REPLACE TABLE RAW.COUNTRIES (
    COUNTRY_CODE VARCHAR(3) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    REGION VARCHAR(50),
    RISK_TIER VARCHAR(20),
    FATF_LISTED BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CUSTOMER_TYPE VARCHAR(20),
    COUNTRY_CODE VARCHAR(3),
    CITY VARCHAR(100),
    RISK_RATING VARCHAR(10),
    PEP_FLAG BOOLEAN DEFAULT FALSE,
    SANCTIONS_FLAG BOOLEAN DEFAULT FALSE,
    INDUSTRY VARCHAR(50),
    ANNUAL_INCOME NUMBER(15,2),
    ONBOARDING_DATE DATE,
    KYC_STATUS VARCHAR(20) DEFAULT 'CURRENT',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BANK_ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES RAW.CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_TYPE VARCHAR(20),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CURRENT_BALANCE NUMBER(15,2),
    OPENED_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BENEFICIARIES (
    BENEFICIARY_ID VARCHAR(20) PRIMARY KEY,
    BENEFICIARY_NAME VARCHAR(100),
    BENEFICIARY_TYPE VARCHAR(30),
    COUNTRY_CODE VARCHAR(3),
    BANK_NAME VARCHAR(100),
    RISK_SCORE NUMBER(5,2) DEFAULT 0,
    TRANSACTION_COUNT NUMBER(10,0) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES RAW.CUSTOMERS(CUSTOMER_ID),
    ACCOUNT_ID VARCHAR(20),
    AMOUNT_USD NUMBER(15,2),
    TRANSACTION_TYPE VARCHAR(20),
    CHANNEL VARCHAR(20),
    DIRECTION VARCHAR(10),
    ORIGIN_COUNTRY VARCHAR(3),
    DESTINATION_COUNTRY VARCHAR(3),
    BENEFICIARY_ID VARCHAR(20),
    IS_SUSPICIOUS BOOLEAN DEFAULT FALSE,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    DESCRIPTION VARCHAR(500),
    REFERENCE_NUMBER VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.AML_SIGNALS (
    SIGNAL_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    SIGNAL_TYPE VARCHAR(30),
    SIGNAL_SCORE NUMBER(5,2),
    RULE_ID VARCHAR(30),
    TRIGGER_DETAIL VARCHAR(1000),
    EVIDENCE_JSON VARIANT,
    TRANSACTION_IDS ARRAY,
    STATUS VARCHAR(20) DEFAULT 'NEW',
    DESCRIPTION VARCHAR(500),
    DETECTION_RUN_ID VARCHAR(20),
    DETECTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RISK_CASES (
    CASE_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    CASE_TYPE VARCHAR(30),
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    PRIORITY VARCHAR(10),
    ASSIGNED_TO VARCHAR(50),
    OPENED_DATE DATE DEFAULT CURRENT_DATE(),
    FINDING_SUMMARY VARCHAR(2000),
    FILING_REFERENCE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CASE_EVIDENCE (
    EVIDENCE_ID VARCHAR(20) PRIMARY KEY,
    CASE_ID VARCHAR(20),
    EVIDENCE_TYPE VARCHAR(30),
    REFERENCE_ID VARCHAR(30),
    DESCRIPTION VARCHAR(1000),
    ADDED_BY VARCHAR(50),
    ADDED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMER_RISK_PROFILE (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    OVERALL_RISK_SCORE NUMBER(5,2),
    GEOGRAPHIC_RISK NUMBER(5,2),
    PRODUCT_RISK NUMBER(5,2),
    BEHAVIOR_RISK NUMBER(5,2),
    EDD_REQUIRED BOOLEAN DEFAULT FALSE,
    LAST_REVIEW_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.POLICY_DOCUMENTS (
    DOC_ID VARCHAR(20) PRIMARY KEY,
    TITLE VARCHAR(200),
    CATEGORY VARCHAR(50),
    JURISDICTION VARCHAR(100),
    FULL_TEXT VARCHAR(16000000),
    EFFECTIVE_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'APPROVED',
    UPLOADED_BY VARCHAR(50),
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.AML_GROUND_TRUTH (
    GROUND_TRUTH_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    IS_TRUE_POSITIVE BOOLEAN,
    ACTUAL_SAR_FILED BOOLEAN DEFAULT FALSE,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CONVERSATION_HISTORY (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CONVERSATION_ID VARCHAR(100),
    USER_ID VARCHAR(100),
    TITLE VARCHAR(500),
    MESSAGE_ROLE VARCHAR(20),
    MESSAGE_CONTENT VARCHAR(16000000),
    MESSAGE_ORDER NUMBER,
    AGENT_THREAD_ID VARCHAR(100),
    AGENT_PARENT_MESSAGE_ID VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- PIPELINE SCHEMA: Operational Tables
-- ============================================================

CREATE OR REPLACE TABLE PIPELINE.SIGNAL_DETECTION_RUNS (
    RUN_ID VARCHAR(30) PRIMARY KEY,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(20),
    RECORDS_PROCESSED NUMBER(10,0) DEFAULT 0,
    SIGNALS_GENERATED NUMBER(10,0) DEFAULT 0
);

CREATE OR REPLACE TABLE PIPELINE.DATA_QUALITY_RESULTS (
    CHECK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CHECK_NAME VARCHAR(100),
    TABLE_NAME VARCHAR(100),
    STATUS VARCHAR(10),
    PASS_RATE NUMBER(7,4),
    RECORDS_CHECKED NUMBER(10,0),
    RECORDS_FAILED NUMBER(10,0),
    OVERALL_PASS_RATE NUMBER(7,4)
);

CREATE OR REPLACE TABLE PIPELINE.GENERATED_REPORTS (
    REPORT_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(20),
    REPORT_TYPE VARCHAR(30),
    FILENAME VARCHAR(200),
    PDF_DATA BINARY,
    GENERATED_BY VARCHAR(50),
    GENERATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PIPELINE.PIPELINE_AUDIT_LOG (
    AUDIT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50),
    EVENT_SOURCE VARCHAR(100),
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID VARCHAR(50),
    DETAIL VARCHAR(2000),
    USER_ID VARCHAR(50),
    LOGGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PIPELINE.POLICY_DOCUMENTS_STAGED (
    DOC_ID VARCHAR(20) PRIMARY KEY,
    TITLE VARCHAR(200),
    CATEGORY VARCHAR(50),
    JURISDICTION VARCHAR(100),
    FULL_TEXT VARCHAR(16000000),
    STATUS VARCHAR(30) DEFAULT 'PENDING_APPROVAL',
    UPLOADED_BY VARCHAR(50),
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_BY VARCHAR(50),
    REVIEWED_AT TIMESTAMP_NTZ,
    REVIEW_NOTES VARCHAR(500)
);

-- ============================================================
-- ANALYTICS SCHEMA: Views
-- ============================================================

CREATE OR REPLACE VIEW ANALYTICS.V_LATEST_DATA_QUALITY AS
SELECT CHECK_NAME, TABLE_NAME, STATUS, PASS_RATE, OVERALL_PASS_RATE
FROM PIPELINE.DATA_QUALITY_RESULTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CHECK_NAME ORDER BY RUN_TIMESTAMP DESC) = 1;

-- ============================================================
-- ANALYTICS SCHEMA: Policy Document Chunks (for Cortex Search)
-- ============================================================

CREATE OR REPLACE TABLE ANALYTICS.POLICY_DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR(30) PRIMARY KEY,
    DOC_ID VARCHAR(20),
    TITLE VARCHAR(200),
    CATEGORY VARCHAR(50),
    JURISDICTION VARCHAR(100),
    CHUNK_TEXT VARCHAR(8000),
    CHUNK_INDEX NUMBER(5,0),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);
