-- ============================================================
-- RiskLens AI - Step 3: Pipeline Objects
-- Streams, Tasks, Stored Procedures
-- ============================================================

USE DATABASE AML_COPILOT;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- STREAM: Track new transactions for incremental detection
-- ============================================================

CREATE OR REPLACE STREAM PIPELINE.STREAM_NEW_TRANSACTIONS
ON TABLE RAW.TRANSACTIONS
APPEND_ONLY = TRUE;

-- ============================================================
-- STORED PROCEDURE: Signal Detection (6 rules)
-- ============================================================
-- NOTE: Full procedure is ~300 lines of SQL. Key rules:
-- RULE_STRUCT_001: 3+ cash txns <$10K summing >$10K in 24h (Structuring)
-- RULE_RAPID_001: Inbound wire >$50K, outbound >80% within 48h (Rapid Movement)
-- RULE_VELOC_001: Txn count >3x 30-day daily average (Velocity Spike)
-- RULE_GEO_001: Txn to HIGH-risk country with no prior history (Unusual Geography)
-- RULE_DORM_001: Txn after 90+ days inactivity (Dormant Activation)
-- RULE_BENEF_001: >5 new beneficiaries in 7 days (Beneficiary Burst)
-- The full DDL is deployed in the Snowflake account. See sp_detect_aml_signals.sql for details.

-- ============================================================
-- STORED PROCEDURE: Data Quality Checks
-- ============================================================
-- Checks: null customer IDs, orphan transactions, negative amounts,
-- duplicate signals, future timestamps, missing risk scores, etc.

-- ============================================================
-- STORED PROCEDURE: Export Report to PDF
-- ============================================================
-- Python stored procedure using fpdf2 for PDF generation
-- Gradient header, formatted tables, evidence sections

-- ============================================================
-- STORED PROCEDURE: Approve Policy Document
-- ============================================================
-- Moves documents from PENDING_APPROVAL to APPROVED in staging table
-- Chunks approved documents into POLICY_DOCUMENT_CHUNKS for Cortex Search

-- ============================================================
-- TASKS: Scheduled execution
-- ============================================================

CREATE OR REPLACE TASK PIPELINE.DETECT_AML_SIGNALS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('AML_COPILOT.PIPELINE.STREAM_NEW_TRANSACTIONS')
AS CALL PIPELINE.SP_DETECT_AML_SIGNALS();

CREATE OR REPLACE TASK PIPELINE.RUN_DATA_QUALITY_CHECKS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '15 MINUTE'
AS CALL PIPELINE.SP_RUN_DATA_QUALITY_CHECKS();

-- Enable tasks
ALTER TASK PIPELINE.DETECT_AML_SIGNALS RESUME;
ALTER TASK PIPELINE.RUN_DATA_QUALITY_CHECKS RESUME;

-- ============================================================
-- DYNAMIC TABLES: Real-time analytics
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_ENRICHED_TRANSACTIONS
    LAG = '5 minutes' REFRESH_MODE = 'AUTO' INITIALIZE = 'ON_CREATE' WAREHOUSE = COMPUTE_WH
AS SELECT
    t.TRANSACTION_ID, t.CUSTOMER_ID, t.ACCOUNT_ID, t.AMOUNT_USD,
    t.TRANSACTION_TYPE, t.CHANNEL, t.DIRECTION,
    t.ORIGIN_COUNTRY, t.DESTINATION_COUNTRY,
    t.BENEFICIARY_ID, t.IS_SUSPICIOUS, t.TRANSACTION_TIMESTAMP,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.CUSTOMER_TYPE, c.RISK_RATING AS CUSTOMER_RISK_RATING,
    c.PEP_FLAG, c.SANCTIONS_FLAG, c.COUNTRY_CODE AS CUSTOMER_COUNTRY,
    dc.RISK_TIER AS DESTINATION_RISK_TIER,
    dc.FATF_LISTED AS DESTINATION_FATF_LISTED,
    b.BENEFICIARY_NAME, b.RISK_SCORE AS BENEFICIARY_RISK_SCORE,
    CASE WHEN dc.RISK_TIER IN ('HIGH','VERY_HIGH') THEN TRUE ELSE FALSE END AS IS_HIGH_RISK_DESTINATION,
    CASE WHEN t.ORIGIN_COUNTRY != t.DESTINATION_COUNTRY THEN TRUE ELSE FALSE END AS IS_CROSS_BORDER
FROM RAW.TRANSACTIONS t
LEFT JOIN RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN RAW.COUNTRIES dc ON t.DESTINATION_COUNTRY = dc.COUNTRY_CODE
LEFT JOIN RAW.BENEFICIARIES b ON t.BENEFICIARY_ID = b.BENEFICIARY_ID;

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_DAILY_SIGNAL_DASHBOARD
    LAG = '5 minutes' REFRESH_MODE = 'AUTO' INITIALIZE = 'ON_CREATE' WAREHOUSE = COMPUTE_WH
AS SELECT
    DATE_TRUNC('DAY', DETECTION_TIMESTAMP)::DATE AS SIGNAL_DATE,
    SIGNAL_TYPE, RULE_ID,
    COUNT(*) AS SIGNAL_COUNT,
    ROUND(AVG(SIGNAL_SCORE), 2) AS AVG_SCORE,
    MAX(SIGNAL_SCORE) AS MAX_SCORE,
    SUM(CASE WHEN STATUS = 'ESCALATED' THEN 1 ELSE 0 END) AS ESCALATED_COUNT,
    SUM(CASE WHEN STATUS = 'NEW' THEN 1 ELSE 0 END) AS NEW_COUNT,
    COUNT(DISTINCT CUSTOMER_ID) AS AFFECTED_CUSTOMERS
FROM RAW.AML_SIGNALS
GROUP BY DATE_TRUNC('DAY', DETECTION_TIMESTAMP)::DATE, SIGNAL_TYPE, RULE_ID;

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_CUSTOMER_RISK_SUMMARY
    LAG = '5 minutes' REFRESH_MODE = 'AUTO' INITIALIZE = 'ON_CREATE' WAREHOUSE = COMPUTE_WH
AS SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.RISK_RATING, c.COUNTRY_CODE AS CUSTOMER_COUNTRY,
    c.PEP_FLAG, c.SANCTIONS_FLAG,
    COUNT(DISTINCT t.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    COALESCE(SUM(t.AMOUNT_USD), 0) AS TOTAL_VOLUME_USD,
    COALESCE(s.TOTAL_SIGNALS, 0) AS TOTAL_SIGNALS,
    COALESCE(s.NEW_SIGNALS, 0) AS NEW_SIGNALS,
    COALESCE(s.MAX_SIGNAL_SCORE, 0) AS MAX_SIGNAL_SCORE,
    COALESCE(rc.TOTAL_CASES, 0) AS TOTAL_CASES,
    COALESCE(rc.OPEN_CASES, 0) AS OPEN_CASES
FROM RAW.CUSTOMERS c
LEFT JOIN RAW.TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS TOTAL_SIGNALS,
        SUM(CASE WHEN STATUS = 'NEW' THEN 1 ELSE 0 END) AS NEW_SIGNALS,
        MAX(SIGNAL_SCORE) AS MAX_SIGNAL_SCORE
    FROM RAW.AML_SIGNALS GROUP BY CUSTOMER_ID
) s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS TOTAL_CASES,
        SUM(CASE WHEN STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_CASES
    FROM RAW.RISK_CASES GROUP BY CUSTOMER_ID
) rc ON c.CUSTOMER_ID = rc.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.RISK_RATING, c.COUNTRY_CODE,
    c.PEP_FLAG, c.SANCTIONS_FLAG, s.TOTAL_SIGNALS, s.NEW_SIGNALS, s.MAX_SIGNAL_SCORE,
    rc.TOTAL_CASES, rc.OPEN_CASES;

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DT_CUSTOMER_RISK_FEATURES
    LAG = '5 minutes' REFRESH_MODE = 'AUTO' INITIALIZE = 'ON_CREATE' WAREHOUSE = COMPUTE_WH
AS SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.RISK_RATING, c.COUNTRY_CODE AS CUSTOMER_COUNTRY,
    COALESCE(SUM(CASE WHEN t.TRANSACTION_TIMESTAMP >= DATEADD('DAY', -7, CURRENT_TIMESTAMP()) THEN 1 END), 0) AS TXN_COUNT_7D,
    COALESCE(SUM(CASE WHEN t.TRANSACTION_TIMESTAMP >= DATEADD('DAY', -7, CURRENT_TIMESTAMP()) THEN t.AMOUNT_USD END), 0) AS TXN_VOLUME_7D,
    COUNT(DISTINCT CASE WHEN t.TRANSACTION_TIMESTAMP >= DATEADD('DAY', -7, CURRENT_TIMESTAMP()) THEN t.BENEFICIARY_ID END) AS UNIQUE_BENEFICIARIES_7D,
    COALESCE(sig.ACTIVE_SIGNAL_COUNT, 0) AS ACTIVE_SIGNAL_COUNT,
    COALESCE(sig.MAX_SIGNAL_SCORE, 0) AS MAX_SIGNAL_SCORE
FROM RAW.CUSTOMERS c
LEFT JOIN RAW.TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) AS ACTIVE_SIGNAL_COUNT, MAX(SIGNAL_SCORE) AS MAX_SIGNAL_SCORE
    FROM RAW.AML_SIGNALS WHERE STATUS IN ('NEW', 'UNDER_REVIEW', 'ESCALATED') GROUP BY CUSTOMER_ID
) sig ON c.CUSTOMER_ID = sig.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.RISK_RATING, c.COUNTRY_CODE,
    sig.ACTIVE_SIGNAL_COUNT, sig.MAX_SIGNAL_SCORE;
