-- ============================================================
-- RiskLens AI - Step 4: Cortex AI Objects
-- Semantic View, Cortex Search, Cortex Agent
-- ============================================================

USE DATABASE AML_COPILOT;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- CORTEX SEARCH SERVICE: Policy Document Search
-- ============================================================

-- First, chunk policy documents into POLICY_DOCUMENT_CHUNKS
INSERT INTO ANALYTICS.POLICY_DOCUMENT_CHUNKS (CHUNK_ID, DOC_ID, TITLE, CATEGORY, JURISDICTION, CHUNK_TEXT, CHUNK_INDEX, STATUS)
SELECT
    'CHK_' || DOC_ID || '_' || 1,
    DOC_ID, TITLE, CATEGORY, JURISDICTION, FULL_TEXT, 1, 'ACTIVE'
FROM RAW.POLICY_DOCUMENTS
WHERE STATUS = 'APPROVED';

CREATE OR REPLACE CORTEX SEARCH SERVICE ANALYTICS.POLICY_SEARCH_SERVICE
    ON CHUNK_TEXT
    ATTRIBUTES TITLE, CATEGORY, JURISDICTION
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT CHUNK_TEXT, TITLE, CATEGORY, JURISDICTION
    FROM ANALYTICS.POLICY_DOCUMENT_CHUNKS
    WHERE STATUS = 'ACTIVE'
);

-- ============================================================
-- SEMANTIC VIEW: 13 tables, 11 relationships, 7 VQRs
-- ============================================================

CREATE OR REPLACE SEMANTIC VIEW RAW.AML_COPILOT_SV

    TABLES (
        RAW.CUSTOMERS PRIMARY KEY (CUSTOMER_ID) COMMENT = 'Master customer registry with KYC data',
        RAW.TRANSACTIONS PRIMARY KEY (TRANSACTION_ID) COMMENT = 'Financial transactions fact table',
        RAW.AML_SIGNALS PRIMARY KEY (SIGNAL_ID) COMMENT = 'Detected AML risk signals',
        RAW.RISK_CASES PRIMARY KEY (CASE_ID) COMMENT = 'Investigation cases',
        RAW.CASE_EVIDENCE PRIMARY KEY (EVIDENCE_ID) COMMENT = 'Evidence items linked to cases',
        RAW.BENEFICIARIES PRIMARY KEY (BENEFICIARY_ID) COMMENT = 'Counterparties that receive funds',
        RAW.COUNTRIES PRIMARY KEY (COUNTRY_CODE) COMMENT = 'Country reference with risk tiers',
        RAW.BANK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID) COMMENT = 'Customer bank accounts',
        RAW.CUSTOMER_RISK_PROFILE PRIMARY KEY (CUSTOMER_ID) COMMENT = 'Composite risk scores per customer',
        ANALYTICS.DT_CUSTOMER_RISK_SUMMARY PRIMARY KEY (CUSTOMER_ID) COMMENT = 'Per-customer summary',
        ANALYTICS.DT_DAILY_SIGNAL_DASHBOARD COMMENT = 'Daily signal metrics',
        PIPELINE.SIGNAL_DETECTION_RUNS PRIMARY KEY (RUN_ID) COMMENT = 'Pipeline run history',
        ANALYTICS.V_LATEST_DATA_QUALITY COMMENT = 'Latest data quality check results'
    )

    RELATIONSHIPS (
        CUST_TO_COUNTRY AS CUSTOMERS(COUNTRY_CODE) REFERENCES COUNTRIES(COUNTRY_CODE),
        TXN_TO_BEN AS TRANSACTIONS(BENEFICIARY_ID) REFERENCES BENEFICIARIES(BENEFICIARY_ID),
        TXN_TO_DEST AS TRANSACTIONS(DESTINATION_COUNTRY) REFERENCES COUNTRIES(COUNTRY_CODE),
        TXN_TO_CUST AS TRANSACTIONS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        SIG_TO_CUST AS AML_SIGNALS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        SIG_TO_RUN AS AML_SIGNALS(DETECTION_RUN_ID) REFERENCES SIGNAL_DETECTION_RUNS(RUN_ID),
        CASE_TO_CUST AS RISK_CASES(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        EV_TO_CASE AS CASE_EVIDENCE(CASE_ID) REFERENCES RISK_CASES(CASE_ID),
        ACCT_TO_CUST AS BANK_ACCOUNTS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        CRP_TO_CUST AS CUSTOMER_RISK_PROFILE(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        SUMMARY_TO_CUST AS DT_CUSTOMER_RISK_SUMMARY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
    )

    FACTS (
        CUSTOMERS.ANNUAL_INCOME AS ANNUAL_INCOME,
        TRANSACTIONS.AMOUNT_USD AS AMOUNT_USD COMMENT = 'Transaction amount in USD',
        AML_SIGNALS.SIGNAL_SCORE AS SIGNAL_SCORE COMMENT = 'Risk score 0-100',
        BENEFICIARIES.BENEFICIARY_RISK_SCORE AS RISK_SCORE,
        BENEFICIARIES.BENEFICIARY_TXN_COUNT AS TRANSACTION_COUNT,
        BANK_ACCOUNTS.CURRENT_BALANCE AS CURRENT_BALANCE,
        CUSTOMER_RISK_PROFILE.OVERALL_RISK_SCORE AS OVERALL_RISK_SCORE COMMENT = 'Overall risk score 0-100',
        CUSTOMER_RISK_PROFILE.GEOGRAPHIC_RISK AS GEOGRAPHIC_RISK,
        CUSTOMER_RISK_PROFILE.PRODUCT_RISK AS PRODUCT_RISK,
        CUSTOMER_RISK_PROFILE.BEHAVIOR_RISK AS BEHAVIOR_RISK,
        DT_CUSTOMER_RISK_SUMMARY.TOTAL_TRANSACTIONS AS TOTAL_TRANSACTIONS,
        DT_CUSTOMER_RISK_SUMMARY.TOTAL_VOLUME_USD AS TOTAL_VOLUME_USD,
        DT_CUSTOMER_RISK_SUMMARY.TOTAL_SIGNALS AS TOTAL_SIGNALS,
        DT_CUSTOMER_RISK_SUMMARY.NEW_SIGNALS AS NEW_SIGNALS,
        DT_CUSTOMER_RISK_SUMMARY.MAX_SIGNAL_SCORE AS MAX_SIGNAL_SCORE,
        DT_CUSTOMER_RISK_SUMMARY.TOTAL_CASES AS TOTAL_CASES,
        DT_CUSTOMER_RISK_SUMMARY.OPEN_CASES AS OPEN_CASES,
        DT_DAILY_SIGNAL_DASHBOARD.SIGNAL_COUNT AS SIGNAL_COUNT,
        DT_DAILY_SIGNAL_DASHBOARD.AVG_SCORE AS AVG_SCORE,
        DT_DAILY_SIGNAL_DASHBOARD.ESCALATED_COUNT AS ESCALATED_COUNT,
        DT_DAILY_SIGNAL_DASHBOARD.AFFECTED_CUSTOMERS AS AFFECTED_CUSTOMERS,
        SIGNAL_DETECTION_RUNS.RECORDS_PROCESSED AS RECORDS_PROCESSED,
        SIGNAL_DETECTION_RUNS.SIGNALS_GENERATED AS SIGNALS_GENERATED,
        V_LATEST_DATA_QUALITY.DQ_PASS_RATE AS PASS_RATE,
        V_LATEST_DATA_QUALITY.DQ_OVERALL_PASS_RATE AS OVERALL_PASS_RATE
    )

    DIMENSIONS (
        CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.FIRST_NAME AS FIRST_NAME,
        CUSTOMERS.LAST_NAME AS LAST_NAME,
        CUSTOMERS.CUSTOMER_TYPE AS CUSTOMER_TYPE SAMPLE_VALUES ('INDIVIDUAL','CORPORATE','TRUST') IS_ENUM,
        CUSTOMERS.COUNTRY_CODE AS COUNTRY_CODE,
        CUSTOMERS.CITY AS CITY,
        CUSTOMERS.RISK_RATING AS RISK_RATING COMMENT = 'AML risk rating' SAMPLE_VALUES ('LOW','MEDIUM','HIGH') IS_ENUM,
        CUSTOMERS.PEP_FLAG AS PEP_FLAG,
        CUSTOMERS.SANCTIONS_FLAG AS SANCTIONS_FLAG,
        CUSTOMERS.INDUSTRY AS INDUSTRY,
        CUSTOMERS.ONBOARDING_DATE AS ONBOARDING_DATE,
        CUSTOMERS.KYC_STATUS AS KYC_STATUS SAMPLE_VALUES ('CURRENT','EXPIRED') IS_ENUM,
        TRANSACTIONS.TRANSACTION_ID AS TRANSACTION_ID,
        TRANSACTIONS.CUSTOMER_ID AS CUSTOMER_ID,
        TRANSACTIONS.ACCOUNT_ID AS ACCOUNT_ID,
        TRANSACTIONS.TRANSACTION_TYPE AS TRANSACTION_TYPE SAMPLE_VALUES ('WIRE','ACH','CASH','CARD','INTERNAL') IS_ENUM,
        TRANSACTIONS.CHANNEL AS CHANNEL SAMPLE_VALUES ('ONLINE','MOBILE','BRANCH','ATM') IS_ENUM,
        TRANSACTIONS.DIRECTION AS DIRECTION SAMPLE_VALUES ('INBOUND','OUTBOUND') IS_ENUM,
        TRANSACTIONS.ORIGIN_COUNTRY AS ORIGIN_COUNTRY,
        TRANSACTIONS.DESTINATION_COUNTRY AS DESTINATION_COUNTRY,
        TRANSACTIONS.BENEFICIARY_ID AS BENEFICIARY_ID,
        TRANSACTIONS.IS_SUSPICIOUS AS IS_SUSPICIOUS,
        TRANSACTIONS.TRANSACTION_TIMESTAMP AS TRANSACTION_TIMESTAMP COMMENT = 'When the transaction occurred',
        AML_SIGNALS.SIGNAL_ID AS SIGNAL_ID,
        AML_SIGNALS.CUSTOMER_ID AS CUSTOMER_ID,
        AML_SIGNALS.SIGNAL_TYPE AS SIGNAL_TYPE SAMPLE_VALUES ('STRUCTURING','RAPID_MOVEMENT','VELOCITY_SPIKE','UNUSUAL_GEOGRAPHY','DORMANT_ACTIVATION','BENEFICIARY_BURST') IS_ENUM,
        AML_SIGNALS.RULE_ID AS RULE_ID COMMENT = 'Detection rule ID' SAMPLE_VALUES ('RULE_STRUCT_001','RULE_RAPID_001','RULE_VELOC_001','RULE_GEO_001','RULE_DORM_001','RULE_BENEF_001') IS_ENUM,
        AML_SIGNALS.TRIGGER_DETAIL AS TRIGGER_DETAIL COMMENT = 'Human-readable trigger explanation',
        AML_SIGNALS.DESCRIPTION AS DESCRIPTION,
        AML_SIGNALS.STATUS AS STATUS SAMPLE_VALUES ('NEW','UNDER_REVIEW','ESCALATED','DISMISSED') IS_ENUM,
        AML_SIGNALS.DETECTION_RUN_ID AS DETECTION_RUN_ID,
        AML_SIGNALS.DETECTION_TIMESTAMP AS DETECTION_TIMESTAMP,
        RISK_CASES.CASE_ID AS CASE_ID,
        RISK_CASES.CUSTOMER_ID AS CUSTOMER_ID,
        RISK_CASES.CASE_TYPE AS CASE_TYPE SAMPLE_VALUES ('SAR','STR','INTERNAL_REVIEW') IS_ENUM,
        RISK_CASES.CASE_STATUS AS STATUS SAMPLE_VALUES ('OPEN','CLOSED','FILED') IS_ENUM,
        RISK_CASES.PRIORITY AS PRIORITY SAMPLE_VALUES ('HIGH','MEDIUM','LOW') IS_ENUM,
        RISK_CASES.ASSIGNED_TO AS ASSIGNED_TO,
        RISK_CASES.OPENED_DATE AS OPENED_DATE,
        RISK_CASES.FINDING_SUMMARY AS FINDING_SUMMARY,
        RISK_CASES.FILING_REFERENCE AS FILING_REFERENCE,
        CASE_EVIDENCE.EVIDENCE_ID AS EVIDENCE_ID,
        CASE_EVIDENCE.CASE_ID AS CASE_ID,
        CASE_EVIDENCE.EVIDENCE_TYPE AS EVIDENCE_TYPE SAMPLE_VALUES ('TRANSACTION','SIGNAL','POLICY') IS_ENUM,
        CASE_EVIDENCE.REFERENCE_ID AS REFERENCE_ID,
        CASE_EVIDENCE.EVIDENCE_DESCRIPTION AS DESCRIPTION,
        CASE_EVIDENCE.ADDED_BY AS ADDED_BY,
        BENEFICIARIES.BENEFICIARY_ID AS BENEFICIARY_ID,
        BENEFICIARIES.BENEFICIARY_NAME AS BENEFICIARY_NAME,
        BENEFICIARIES.BENEFICIARY_TYPE AS BENEFICIARY_TYPE,
        BENEFICIARIES.COUNTRY_CODE AS COUNTRY_CODE,
        BENEFICIARIES.BANK_NAME AS BANK_NAME,
        COUNTRIES.COUNTRY_CODE AS COUNTRY_CODE,
        COUNTRIES.COUNTRY_NAME AS COUNTRY_NAME,
        COUNTRIES.REGION AS REGION,
        COUNTRIES.RISK_TIER AS RISK_TIER SAMPLE_VALUES ('LOW','MEDIUM','HIGH','VERY_HIGH') IS_ENUM,
        COUNTRIES.FATF_LISTED AS FATF_LISTED,
        BANK_ACCOUNTS.ACCOUNT_ID AS ACCOUNT_ID,
        BANK_ACCOUNTS.CUSTOMER_ID AS CUSTOMER_ID,
        BANK_ACCOUNTS.ACCOUNT_TYPE AS ACCOUNT_TYPE SAMPLE_VALUES ('CHECKING','SAVINGS','CREDIT','LOAN') IS_ENUM,
        BANK_ACCOUNTS.ACCOUNT_STATUS AS STATUS SAMPLE_VALUES ('ACTIVE','DORMANT','CLOSED') IS_ENUM,
        CUSTOMER_RISK_PROFILE.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMER_RISK_PROFILE.EDD_REQUIRED AS EDD_REQUIRED,
        DT_CUSTOMER_RISK_SUMMARY.CUSTOMER_ID AS CUSTOMER_ID,
        DT_CUSTOMER_RISK_SUMMARY.CUSTOMER_NAME AS CUSTOMER_NAME,
        DT_CUSTOMER_RISK_SUMMARY.RISK_RATING AS RISK_RATING,
        DT_CUSTOMER_RISK_SUMMARY.CUSTOMER_COUNTRY AS CUSTOMER_COUNTRY,
        DT_DAILY_SIGNAL_DASHBOARD.SIGNAL_DATE AS SIGNAL_DATE,
        DT_DAILY_SIGNAL_DASHBOARD.SIGNAL_TYPE AS SIGNAL_TYPE,
        DT_DAILY_SIGNAL_DASHBOARD.RULE_ID AS RULE_ID,
        SIGNAL_DETECTION_RUNS.RUN_ID AS RUN_ID,
        SIGNAL_DETECTION_RUNS.START_TIME AS START_TIME,
        SIGNAL_DETECTION_RUNS.RUN_STATUS AS STATUS SAMPLE_VALUES ('COMPLETED','FAILED','RUNNING') IS_ENUM,
        V_LATEST_DATA_QUALITY.CHECK_NAME AS CHECK_NAME,
        V_LATEST_DATA_QUALITY.DQ_TABLE_NAME AS TABLE_NAME,
        V_LATEST_DATA_QUALITY.DQ_STATUS AS STATUS
    )

    COMMENT = 'Anti-Money Laundering risk monitoring, signal investigation, policy compliance, and operational analytics'

    AI_SQL_GENERATION 'PREFER pre-computed tables: DT_CUSTOMER_RISK_SUMMARY for customer overviews, DT_DAILY_SIGNAL_DASHBOARD for signal trends, V_LATEST_DATA_QUALITY for DQ status. Always include RULE_ID and TRIGGER_DETAIL when showing signal details. Round numeric values to 2 decimal places.'

    AI_VERIFIED_QUERIES (
        total_signals AS (
            QUESTION 'How many AML signals are there?'
            VERIFIED_AT 1791065000
            ONBOARDING_QUESTION TRUE
            SQL 'SELECT COUNT(*) AS TOTAL_SIGNALS FROM AML_COPILOT.RAW.AML_SIGNALS'
        ),
        signals_by_type AS (
            QUESTION 'Show AML signals by type'
            VERIFIED_AT 1791065000
            ONBOARDING_QUESTION TRUE
            SQL 'SELECT SIGNAL_TYPE, COUNT(*) AS SIGNAL_COUNT, ROUND(AVG(SIGNAL_SCORE),2) AS AVG_SCORE FROM AML_COPILOT.RAW.AML_SIGNALS GROUP BY SIGNAL_TYPE ORDER BY SIGNAL_COUNT DESC'
        ),
        high_risk_customers AS (
            QUESTION 'Which customers have the highest risk?'
            VERIFIED_AT 1791065000
            ONBOARDING_QUESTION TRUE
            SQL 'SELECT CUSTOMER_ID, CUSTOMER_NAME, RISK_RATING, TOTAL_SIGNALS, MAX_SIGNAL_SCORE, TOTAL_VOLUME_USD, OPEN_CASES FROM AML_COPILOT.ANALYTICS.DT_CUSTOMER_RISK_SUMMARY WHERE TOTAL_SIGNALS > 0 ORDER BY MAX_SIGNAL_SCORE DESC, TOTAL_SIGNALS DESC LIMIT 10'
        ),
        open_cases AS (
            QUESTION 'How many open investigation cases are there?'
            VERIFIED_AT 1791065000
            SQL 'SELECT COUNT(*) AS OPEN_CASES FROM AML_COPILOT.RAW.RISK_CASES WHERE STATUS = ''OPEN'''
        ),
        signal_trends AS (
            QUESTION 'What are the daily signal trends?'
            VERIFIED_AT 1791065000
            ONBOARDING_QUESTION TRUE
            SQL 'SELECT SIGNAL_DATE, SUM(SIGNAL_COUNT) AS TOTAL_SIGNALS, ROUND(AVG(AVG_SCORE),2) AS AVG_SCORE, SUM(ESCALATED_COUNT) AS ESCALATED FROM AML_COPILOT.ANALYTICS.DT_DAILY_SIGNAL_DASHBOARD GROUP BY SIGNAL_DATE ORDER BY SIGNAL_DATE DESC LIMIT 30'
        ),
        data_quality_status AS (
            QUESTION 'What is the data quality status?'
            VERIFIED_AT 1791065000
            SQL 'SELECT CHECK_NAME, TABLE_NAME, STATUS, PASS_RATE, OVERALL_PASS_RATE FROM AML_COPILOT.ANALYTICS.V_LATEST_DATA_QUALITY ORDER BY PASS_RATE ASC'
        ),
        new_signals AS (
            QUESTION 'How many new unreviewed signals are there?'
            VERIFIED_AT 1791065000
            SQL 'SELECT COUNT(*) AS NEW_SIGNALS FROM AML_COPILOT.RAW.AML_SIGNALS WHERE STATUS = ''NEW'''
        )
    );


-- ============================================================
-- CORTEX AGENT: AML Risk Copilot
-- ============================================================

CREATE OR REPLACE AGENT RAW.AML_RISK_COPILOT
    COMMENT = 'AML Risk Investigation Copilot - policy-backed, evidence-driven answers'
    FROM SPECIFICATION
$$
models:
  orchestration: auto

orchestration:
  tool_not_accessible: accept
  budget:
    seconds: 120
    tokens: 100000

instructions:
  orchestration: |
    You are the AML Risk Copilot for an enterprise compliance team. You surface risk and fraud signals and produce audit-ready regulatory outputs from natural language questions.

    CORE PRINCIPLE: Every answer MUST be policy-backed and evidence-driven.
    - ALWAYS use BOTH tools for every question: query data with risk_analytics AND search policies with policy_search.
    - NEVER answer a question using only one tool. Every response must combine DATA EVIDENCE + POLICY CITATION.

    RESPONSE STRUCTURE:
    1. **Summary**: Direct answer in 2-3 sentences.
    2. **Evidence**: Data that supports the answer with specific numbers.
    3. **Applicable Policy**: Which AML/BSA/FATF policy applies, with specific section and requirement.
    4. **Risk Assessment**: Risk level grounded in both data and policy.
    5. **Recommended Action**: What the compliance analyst should do next.

  response: |
    Structure every response with clear sections. Use tables for multi-row data.
    Always include RULE_ID and TRIGGER_DETAIL when showing signal details.
    Cite policy documents by exact TITLE and JURISDICTION.
    End every response with confidence assessment: HIGH, MEDIUM, or LOW.

tools:
  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: risk_analytics
      description: |
        Queries AML Copilot structured data: customers, transactions, signals, cases, risk scores, pipeline health.
  - tool_spec:
      type: cortex_search
      name: policy_search
      description: |
        Searches 11 AML regulatory policy documents: BSA/AML CTR, SAR filing, EDD, wire monitoring, sanctions, KYC, UAE AML/CFT, CTF, TBML, correspondent banking.

tool_resources:
  risk_analytics:
    semantic_view: AML_COPILOT.RAW.AML_COPILOT_SV
    execution_environment:
      type: warehouse
      warehouse: COMPUTE_WH
  policy_search:
    search_service: AML_COPILOT.ANALYTICS.POLICY_SEARCH_SERVICE
    max_results: "5"
    title_column: TITLE
    columns_and_descriptions:
      CHUNK_TEXT:
        description: "Full text of the policy document"
        type: "string"
        searchable: true
        filterable: false
      TITLE:
        description: "Policy title"
        type: "string"
        searchable: true
        filterable: true
      CATEGORY:
        description: "Policy category"
        type: "string"
        searchable: false
        filterable: true
      JURISDICTION:
        description: "Jurisdiction"
        type: "string"
        searchable: false
        filterable: true
$$;
